import {
  Document,
  Page,
  Text,
  View,
  Image,
} from "@react-pdf/renderer";
import { registerPdfFonts } from "./invoice-pdf-fonts";
import { buildPdfStyles } from "./invoice-pdf-styles";
import type { Invoice } from "@/types";
import type { Settings } from "@/lib/api/settings";
import type { InvoiceDesign } from "@/lib/invoice-design";
import { DEFAULT_INVOICE_DESIGN } from "@/lib/invoice-design";

interface InvoicePdfDocumentProps {
  invoice: Invoice;
  settings: Settings;
  design?: InvoiceDesign;
  qrCodeDataUrl?: string;
  logoDataUrl?: string;
}

function getInvoiceTypeLabel(type?: string): { ar: string; en: string } {
  switch (type) {
    case "credit_note":
      return { ar: "إشعار دائن", en: "Credit Note" };
    case "debit_note":
      return { ar: "إشعار مدين", en: "Debit Note" };
    case "simplified":
      return { ar: "فاتورة ضريبية مبسطة", en: "Simplified Tax Invoice" };
    default:
      return { ar: "فاتورة ضريبية", en: "Tax Invoice" };
  }
}

function getTaxBreakdown(invoice: Invoice) {
  const groups: Record<number, { taxableAmount: number; vatAmount: number }> = {};
  for (const item of invoice.items) {
    const rate = item.taxRate ?? invoice.taxRate;
    if (!groups[rate]) groups[rate] = { taxableAmount: 0, vatAmount: 0 };
    const lineNet = item.total - (item.taxAmount ?? 0);
    groups[rate].taxableAmount += lineNet;
    groups[rate].vatAmount += item.taxAmount ?? 0;
  }
  return Object.entries(groups).map(([rate, data]) => ({
    rate: Number(rate),
    ...data,
  }));
}

function fmt(v: number) {
  return v.toFixed(2);
}

export function InvoicePdfDocument({
  invoice,
  settings,
  design = DEFAULT_INVOICE_DESIGN,
  qrCodeDataUrl,
  logoDataUrl,
}: InvoicePdfDocumentProps) {
  registerPdfFonts();
  const s = buildPdfStyles(design);
  const typeLabel = getInvoiceTypeLabel(invoice.invoiceType);
  const taxBreakdown = getTaxBreakdown(invoice);
  const currency = invoice.currency || settings.currency || "";
  const taxableAmount = invoice.subtotal - (invoice.discountTotal ?? 0);

  const isModern = design.template === "modern";
  const isCompact = design.template === "compact";
  const useInlineHeader = design.headerLayout === "inline" || isModern || isCompact;

  const defaultFooterAr = `تم الإنشاء بواسطة ${settings.businessName}`;
  const defaultFooterEn = `Generated by ${settings.businessNameEn || settings.businessName}`;

  return (
    <Document>
      <Page size="A4" style={s.page}>
        {/* Header */}
        <View style={s.header}>
          {!useInlineHeader && logoDataUrl && <Image src={logoDataUrl} style={s.logo} />}
          <View style={s.headerTextBlock}>
            <Text style={s.bizName}>{settings.businessName}</Text>
            {settings.businessNameEn && (
              <Text style={s.bizNameEn}>{settings.businessNameEn}</Text>
            )}
            {design.tagline ? <Text style={s.tagline}>{design.tagline}</Text> : null}
            {design.taglineEn ? <Text style={[s.tagline, { fontSize: (design.bodyFontSize || 10) - 2 }]}>{design.taglineEn}</Text> : null}
            {settings.businessAddress && (
              <Text style={s.headerDetail}>{settings.businessAddress}</Text>
            )}
            {settings.businessPhone && (
              <Text style={s.headerDetail}>{settings.businessPhone}</Text>
            )}
            {(settings.taxRegistrationNumber || settings.taxNumber) && (
              <Text style={s.trn}>
                الرقم الضريبي / TRN: {settings.taxRegistrationNumber || settings.taxNumber}
              </Text>
            )}
          </View>
          {useInlineHeader && logoDataUrl && <Image src={logoDataUrl} style={s.logo} />}
        </View>

        {/* Modern accent bar */}
        {isModern && <View style={s.accentBar} />}

        {/* Type Badge */}
        <View style={s.typeBadge}>
          <Text style={s.typeAr}>{typeLabel.ar}</Text>
          <Text style={s.typeEn}>{typeLabel.en}</Text>
        </View>

        {/* Meta */}
        <View style={s.metaRow}>
          <Text>
            <Text style={s.metaLabel}>رقم الفاتورة / Invoice #: </Text>
            <Text>{invoice.invoiceNumber}</Text>
          </Text>
          <Text>
            <Text style={s.metaLabel}>التاريخ / Date: </Text>
            <Text>{invoice.date}</Text>
          </Text>
        </View>
        {design.showUuid && invoice.uuid && <Text style={s.uuid}>UUID: {invoice.uuid}</Text>}

        {/* Buyer Info (B2B) */}
        {(invoice.buyerName || invoice.buyerTrn) && (
          <View style={s.buyerBox}>
            <Text style={s.buyerTitle}>معلومات المشتري / Buyer Information</Text>
            {invoice.buyerName && (
              <Text style={s.buyerLine}>الاسم / Name: {invoice.buyerName}</Text>
            )}
            {invoice.buyerTrn && (
              <Text style={s.buyerLine}>الرقم الضريبي / TRN: {invoice.buyerTrn}</Text>
            )}
            {invoice.buyerAddress && (
              <Text style={s.buyerLine}>العنوان / Address: {invoice.buyerAddress}</Text>
            )}
          </View>
        )}

        {/* Client Info (B2C) */}
        {!invoice.buyerName && (
          <Text style={s.clientLine}>
            <Text style={s.metaLabel}>العميل / Client: </Text>
            {invoice.clientName} — {invoice.clientPhone}
          </Text>
        )}

        {/* Items Table */}
        <View style={s.table}>
          <View style={s.tableHeaderRow}>
            <View style={s.colNum}><Text style={s.thText}>#</Text></View>
            <View style={s.colDesc}>
              <Text style={s.thText}>الوصف</Text>
              <Text style={s.thTextEn}>Description</Text>
            </View>
            <View style={s.colQty}>
              <Text style={s.thText}>الكمية</Text>
              <Text style={s.thTextEn}>Qty</Text>
            </View>
            <View style={s.colPrice}>
              <Text style={s.thText}>السعر</Text>
              <Text style={s.thTextEn}>Price</Text>
            </View>
            <View style={s.colDisc}>
              <Text style={s.thText}>الخصم</Text>
              <Text style={s.thTextEn}>Discount</Text>
            </View>
            <View style={s.colTaxPct}>
              <Text style={s.thText}>ض %</Text>
              <Text style={s.thTextEn}>Tax%</Text>
            </View>
            <View style={s.colTaxAmt}>
              <Text style={s.thText}>مبلغ الضريبة</Text>
              <Text style={s.thTextEn}>Tax Amt</Text>
            </View>
            <View style={s.colTotal}>
              <Text style={s.thText}>الإجمالي</Text>
              <Text style={s.thTextEn}>Total</Text>
            </View>
          </View>

          {invoice.items.map((item, i) => (
            <View key={i} style={isCompact && i % 2 === 1 ? s.tableRowAlt : s.tableRow}>
              <View style={s.colNum}><Text style={s.tdText}>{i + 1}</Text></View>
              <View style={s.colDesc}><Text style={s.tdTextAr}>{item.description}</Text></View>
              <View style={s.colQty}><Text style={s.tdText}>{item.quantity}</Text></View>
              <View style={s.colPrice}><Text style={s.tdText}>{fmt(item.unitPrice)}</Text></View>
              <View style={s.colDisc}><Text style={s.tdText}>{fmt(item.discount)}</Text></View>
              <View style={s.colTaxPct}><Text style={s.tdText}>{item.taxRate ?? invoice.taxRate}%</Text></View>
              <View style={s.colTaxAmt}><Text style={s.tdText}>{fmt(item.taxAmount ?? 0)}</Text></View>
              <View style={s.colTotal}><Text style={s.tdText}>{fmt(item.total)}</Text></View>
            </View>
          ))}
        </View>

        {/* Tax Breakdown */}
        {design.showTaxBreakdown && taxBreakdown.length > 0 && (
          <View style={s.taxSection}>
            <Text style={s.taxTitle}>تفصيل الضريبة / Tax Breakdown</Text>
            <View style={s.tableHeaderRow}>
              <Text style={s.taxColHeader}>النسبة / Rate</Text>
              <Text style={s.taxColHeader}>المبلغ الخاضع / Taxable</Text>
              <Text style={s.taxColHeader}>الضريبة / VAT</Text>
            </View>
            {taxBreakdown.map((row, i) => (
              <View key={i} style={s.taxRow}>
                <Text style={s.taxCol}>{row.rate}%</Text>
                <Text style={s.taxCol}>{fmt(row.taxableAmount)}</Text>
                <Text style={s.taxCol}>{fmt(row.vatAmount)}</Text>
              </View>
            ))}
          </View>
        )}

        {/* Totals */}
        <View style={s.totalsWrap}>
          <View style={s.totalsTable}>
            <View style={s.totalsRow}>
              <Text style={s.totalsLabel}>المجموع / Subtotal</Text>
              <Text style={s.totalsValue}>{fmt(invoice.subtotal)} {currency}</Text>
            </View>
            {(invoice.discountTotal ?? 0) > 0 && (
              <View style={s.totalsRow}>
                <Text style={s.totalsLabel}>الخصم / Discount</Text>
                <Text style={s.totalsValue}>-{fmt(invoice.discountTotal!)} {currency}</Text>
              </View>
            )}
            <View style={s.totalsRow}>
              <Text style={s.totalsLabel}>المبلغ الخاضع / Taxable</Text>
              <Text style={s.totalsValue}>{fmt(taxableAmount)} {currency}</Text>
            </View>
            <View style={s.totalsRow}>
              <Text style={s.totalsLabel}>الضريبة / VAT ({invoice.taxRate}%)</Text>
              <Text style={s.totalsValue}>{fmt(invoice.taxAmount)} {currency}</Text>
            </View>
            <View style={s.grandTotalRow}>
              <Text style={s.grandTotalLabel}>الإجمالي / Grand Total</Text>
              <Text style={s.grandTotalValue}>{fmt(invoice.total)} {currency}</Text>
            </View>
          </View>
        </View>

        {/* QR Code */}
        {design.showQrCode && qrCodeDataUrl && (
          <View style={s.qrWrap}>
            <Image src={qrCodeDataUrl} style={s.qrImage} />
          </View>
        )}

        {/* Notes */}
        {design.showNotes && invoice.notes && (
          <View style={s.notesBox}>
            <Text style={s.notesTitle}>ملاحظات / Notes:</Text>
            <Text>{invoice.notes}</Text>
          </View>
        )}

        {/* Footer */}
        <Text style={s.footer}>
          {design.footerText || design.footerTextEn
            ? `${design.footerText}${design.footerText && design.footerTextEn ? " / " : ""}${design.footerTextEn}`
            : `${defaultFooterAr} / ${defaultFooterEn}`}
        </Text>
      </Page>
    </Document>
  );
}

export async function imageUrlToDataUrl(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const img = new window.Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;
      const ctx = canvas.getContext("2d");
      if (!ctx) return reject(new Error("Canvas context unavailable"));
      ctx.drawImage(img, 0, 0);
      resolve(canvas.toDataURL("image/png"));
    };
    img.onerror = () => reject(new Error("Failed to load image"));
    img.src = url;
  });
}
