"use client";

import { Invoice } from "@/types";
import { Settings } from "@/lib/api/settings";
import { QrCodeImage } from "./qr-code-image";
import type { InvoiceDesign } from "@/lib/invoice-design";
import { DEFAULT_INVOICE_DESIGN, SPACING_MULTIPLIERS, CSS_FONT_MAP } from "@/lib/invoice-design";

interface InvoicePrintViewProps {
  invoice: Invoice;
  settings: Settings;
  design?: InvoiceDesign;
}

function getInvoiceTypeLabel(invoice: Invoice): { ar: string; en: string } {
  switch (invoice.invoiceType) {
    case "credit_note":
      return { ar: "إشعار دائن", en: "Credit Note" };
    case "debit_note":
      return { ar: "إشعار مدين", en: "Debit Note" };
    case "simplified":
      return { ar: "فاتورة ضريبية مبسطة", en: "Simplified Tax Invoice" };
    default:
      return { ar: "فاتورة ضريبية", en: "Tax Invoice" };
  }
}

function getTaxBreakdown(invoice: Invoice) {
  const groups: Record<number, { taxableAmount: number; vatAmount: number }> = {};
  for (const item of invoice.items) {
    const rate = item.taxRate ?? invoice.taxRate;
    if (!groups[rate]) groups[rate] = { taxableAmount: 0, vatAmount: 0 };
    const lineNet = item.total - (item.taxAmount ?? 0);
    groups[rate].taxableAmount += lineNet;
    groups[rate].vatAmount += item.taxAmount ?? 0;
  }
  return Object.entries(groups).map(([rate, data]) => ({
    rate: Number(rate),
    ...data,
  }));
}

function formatCurrency(value: number, currency?: string) {
  return `${value.toFixed(2)} ${currency || ""}`.trim();
}

/* =============================================
   A4 Layout — uses inline styles (same as preview)
   ============================================= */
function A4View({ invoice, settings, design }: { invoice: Invoice; settings: Settings; design: InvoiceDesign }) {
  const typeLabel = getInvoiceTypeLabel(invoice);
  const taxBreakdown = getTaxBreakdown(invoice);
  const currency = invoice.currency || settings.currency || "";
  const taxableAmount = invoice.subtotal - (invoice.discountTotal ?? 0);
  const logoUrl = settings.logoUrl;
  const sp = SPACING_MULTIPLIERS[design.sectionSpacing];

  const isModern = design.template === "modern";
  const isElegant = design.template === "elegant";
  const isCompact = design.template === "compact";

  const fontFamily = CSS_FONT_MAP[design.fontFamily];
  const tableHeaderBg = isModern ? design.accentColor : isElegant ? "transparent" : design.secondaryColor;
  const tableHeaderColor = isModern ? "#fff" : "#000";
  const headerBorder = isElegant
    ? `1px solid ${design.accentColor}`
    : isCompact
      ? "none"
      : `2px solid ${design.primaryColor}`;

  const defaultFooterAr = `تم الإنشاء بواسطة ${settings.businessName}`;
  const defaultFooterEn = `Generated by ${settings.businessNameEn || settings.businessName}`;

  return (
    <div
      className="print-a4-view"
      dir="rtl"
      style={{
        fontFamily,
        fontSize: design.bodyFontSize,
        color: "#1a1a1a",
        background: "#fff",
        padding: design.pageMargin,
        minHeight: "297mm",
      }}
    >
      {/* Header */}
      <div
        style={{
          textAlign: isModern || isCompact ? "initial" : "center",
          marginBottom: 16 * sp,
          borderBottom: headerBorder,
          paddingBottom: 12 * sp,
          ...(isModern || isCompact
            ? { display: "flex", flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }
            : {}),
        }}
      >
        {logoUrl && (
          <img
            src={logoUrl}
            alt=""
            style={{
              display: "block",
              width: isCompact ? 80 : 120,
              maxHeight: isCompact ? 40 : 60,
              objectFit: "contain",
              ...(design.logoPosition === "center" && !isModern && !isCompact
                ? { margin: "0 auto 8px" }
                : design.logoPosition === "left" && !isModern && !isCompact
                  ? { marginLeft: "auto", marginBottom: 8 }
                  : { marginBottom: isModern || isCompact ? 0 : 8 }),
            }}
          />
        )}
        <div style={{ textAlign: isModern || isCompact ? "right" : "center", flex: isModern || isCompact ? 1 : undefined }}>
          <div style={{ fontSize: design.businessNameSize, fontWeight: 700, marginBottom: 2 }}>
            {settings.businessName}
          </div>
          {settings.businessNameEn && (
            <div style={{ fontSize: Math.round(design.businessNameSize * 0.67), fontFamily: "'Outfit', sans-serif", color: "#444", marginBottom: 6, direction: "ltr" }}>
              {settings.businessNameEn}
            </div>
          )}
          {design.tagline && (
            <div style={{ fontSize: design.bodyFontSize - 1, color: design.accentColor, marginBottom: 2 }}>
              {design.tagline}
            </div>
          )}
          {design.taglineEn && (
            <div style={{ fontSize: design.bodyFontSize - 2, color: design.accentColor, direction: "ltr", marginBottom: 2 }}>
              {design.taglineEn}
            </div>
          )}
          {settings.businessAddress && (
            <div style={{ fontSize: design.bodyFontSize - 1, color: "#555" }}>{settings.businessAddress}</div>
          )}
          {settings.businessPhone && (
            <div style={{ fontSize: design.bodyFontSize - 1, color: "#555", direction: "ltr" }}>{settings.businessPhone}</div>
          )}
          {(settings.taxRegistrationNumber || settings.taxNumber) && (
            <div style={{ fontSize: design.bodyFontSize, fontWeight: 700, marginTop: 4 }}>
              الرقم الضريبي / TRN: {settings.taxRegistrationNumber || settings.taxNumber}
            </div>
          )}
        </div>
      </div>

      {/* Modern accent bar */}
      {isModern && (
        <div style={{ height: 3, backgroundColor: design.accentColor, marginBottom: 12 * sp }} />
      )}

      {/* Type Badge */}
      <div
        style={{
          textAlign: "center",
          margin: `${12 * sp}px 0`,
          padding: isCompact ? "3px 8px" : "6px 12px",
          ...(isModern
            ? { backgroundColor: design.accentColor, borderRadius: 20 }
            : isElegant
              ? { borderBottom: `1px solid ${design.accentColor}`, background: "transparent" }
              : isCompact
                ? { backgroundColor: design.secondaryColor, borderRadius: 4 }
                : { backgroundColor: design.secondaryColor, border: "1px solid #ddd" }),
        }}
      >
        <strong style={{
          fontSize: isCompact ? 11 : 14,
          ...(isModern ? { color: "#fff" } : {}),
          ...(isElegant ? { textDecoration: "underline", textDecorationColor: design.accentColor } : {}),
        }}>
          {typeLabel.ar}
        </strong>
        <br />
        <span style={{
          fontSize: isCompact ? 8 : 10,
          fontFamily: "'Outfit', sans-serif",
          ...(isModern ? { color: "rgba(255,255,255,0.8)" } : { color: "#555" }),
        }}>
          {typeLabel.en}
        </span>
      </div>

      {/* Meta */}
      <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 12 * sp, fontSize: design.bodyFontSize }}>
        <span><strong>رقم الفاتورة / Invoice #: </strong><span style={{ fontFamily: "'Outfit', sans-serif" }}>{invoice.invoiceNumber}</span></span>
        <span><strong>التاريخ / Date: </strong><span style={{ fontFamily: "'Outfit', sans-serif" }}>{invoice.date}</span></span>
      </div>
      {design.showUuid && invoice.uuid && (
        <div style={{ fontSize: 7, color: "#888", textAlign: "center", marginBottom: 8 * sp, fontFamily: "'Outfit', sans-serif" }}>
          UUID: {invoice.uuid}
        </div>
      )}

      {/* Buyer Info (B2B) */}
      {(invoice.buyerName || invoice.buyerTrn) && (
        <div style={{ marginBottom: 12 * sp, padding: 8, border: "1px solid #ddd" }}>
          <strong style={{ fontSize: design.bodyFontSize }}>معلومات المشتري / Buyer Information</strong>
          <div style={{ marginTop: 5, fontSize: design.bodyFontSize - 1, color: "#333" }}>
            {invoice.buyerName && <div><strong>الاسم / Name:</strong> {invoice.buyerName}</div>}
            {invoice.buyerTrn && <div><strong>الرقم الضريبي / TRN:</strong> <span style={{ fontFamily: "'Outfit', sans-serif" }}>{invoice.buyerTrn}</span></div>}
            {invoice.buyerAddress && <div><strong>العنوان / Address:</strong> {invoice.buyerAddress}</div>}
          </div>
        </div>
      )}

      {/* Client Info (B2C) */}
      {!invoice.buyerName && (
        <div style={{ fontSize: design.bodyFontSize, marginBottom: 12 * sp, color: "#333" }}>
          <strong>العميل / Client: </strong>{invoice.clientName} — <span style={{ fontFamily: "'Outfit', sans-serif" }}>{invoice.clientPhone}</span>
        </div>
      )}

      {/* Items Table */}
      <table style={{ width: "100%", borderCollapse: "collapse", marginBottom: 12 * sp }}>
        <thead>
          <tr style={{
            backgroundColor: tableHeaderBg,
            borderBottom: isElegant ? `2px solid ${design.accentColor}` : `2px solid ${design.primaryColor}`,
          }}>
            {[
              { ar: "#", en: "", align: "center" as const },
              { ar: "الوصف", en: "Description", align: "right" as const },
              { ar: "الكمية", en: "Qty", align: "center" as const },
              { ar: "السعر", en: "Price", align: "center" as const },
              { ar: "الخصم", en: "Discount", align: "center" as const },
              { ar: "ض %", en: "Tax %", align: "center" as const },
              { ar: "مبلغ الضريبة", en: "Tax Amt", align: "center" as const },
              { ar: "الإجمالي", en: "Total", align: "center" as const },
            ].map((h, i) => (
              <th key={i} style={{
                padding: isCompact ? 3 : 5,
                textAlign: h.align,
                fontSize: design.tableHeaderSize,
                fontWeight: 700,
                color: tableHeaderColor,
              }}>
                {h.ar}
                {h.en && <><br /><span style={{ fontSize: design.tableHeaderSize - 2, fontWeight: 400, fontFamily: "'Outfit', sans-serif", color: isModern ? "rgba(255,255,255,0.7)" : "#666" }}>{h.en}</span></>}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {invoice.items.map((item, i) => (
            <tr key={i} style={{
              borderBottom: "1px solid #eee",
              backgroundColor: isCompact && i % 2 === 1 ? design.secondaryColor : undefined,
            }}>
              <td style={{ padding: isCompact ? 3 : 4, textAlign: "center", fontSize: design.bodyFontSize - 1, fontFamily: "'Outfit', sans-serif" }}>{i + 1}</td>
              <td style={{ padding: isCompact ? 3 : 4, textAlign: "right", fontSize: design.bodyFontSize - 1 }}>{item.description}</td>
              <td style={{ padding: isCompact ? 3 : 4, textAlign: "center", fontSize: design.bodyFontSize - 1, fontFamily: "'Outfit', sans-serif" }}>{item.quantity}</td>
              <td style={{ padding: isCompact ? 3 : 4, textAlign: "center", fontSize: design.bodyFontSize - 1, fontFamily: "'Outfit', sans-serif" }}>{item.unitPrice.toFixed(2)}</td>
              <td style={{ padding: isCompact ? 3 : 4, textAlign: "center", fontSize: design.bodyFontSize - 1, fontFamily: "'Outfit', sans-serif" }}>{item.discount.toFixed(2)}</td>
              <td style={{ padding: isCompact ? 3 : 4, textAlign: "center", fontSize: design.bodyFontSize - 1, fontFamily: "'Outfit', sans-serif" }}>{item.taxRate ?? invoice.taxRate}%</td>
              <td style={{ padding: isCompact ? 3 : 4, textAlign: "center", fontSize: design.bodyFontSize - 1, fontFamily: "'Outfit', sans-serif" }}>{(item.taxAmount ?? 0).toFixed(2)}</td>
              <td style={{ padding: isCompact ? 3 : 4, textAlign: "center", fontSize: design.bodyFontSize - 1, fontFamily: "'Outfit', sans-serif" }}>{item.total.toFixed(2)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Tax Breakdown */}
      {design.showTaxBreakdown && taxBreakdown.length > 0 && (
        <div style={{ marginBottom: 12 * sp }}>
          <strong style={{ fontSize: design.bodyFontSize }}>تفصيل الضريبة / Tax Breakdown</strong>
          <table style={{ width: "50%", borderCollapse: "collapse", marginTop: 5 }}>
            <thead>
              <tr style={{ backgroundColor: tableHeaderBg, borderBottom: `2px solid ${design.primaryColor}` }}>
                <th style={{ padding: 4, fontSize: design.tableHeaderSize, fontWeight: 700, color: tableHeaderColor }}>النسبة / Rate</th>
                <th style={{ padding: 4, fontSize: design.tableHeaderSize, fontWeight: 700, textAlign: "center", color: tableHeaderColor }}>المبلغ الخاضع / Taxable</th>
                <th style={{ padding: 4, fontSize: design.tableHeaderSize, fontWeight: 700, textAlign: "center", color: tableHeaderColor }}>الضريبة / VAT</th>
              </tr>
            </thead>
            <tbody>
              {taxBreakdown.map((row, i) => (
                <tr key={i} style={{ borderBottom: "1px solid #eee" }}>
                  <td style={{ padding: 3, fontSize: design.bodyFontSize - 1, fontFamily: "'Outfit', sans-serif" }}>{row.rate}%</td>
                  <td style={{ padding: 3, fontSize: design.bodyFontSize - 1, textAlign: "center", fontFamily: "'Outfit', sans-serif" }}>{row.taxableAmount.toFixed(2)}</td>
                  <td style={{ padding: 3, fontSize: design.bodyFontSize - 1, textAlign: "center", fontFamily: "'Outfit', sans-serif" }}>{row.vatAmount.toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Totals */}
      <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: 16 * sp }}>
        <div style={{ width: "45%" }}>
          <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid #eee", padding: "3px 0" }}>
            <span style={{ fontSize: design.bodyFontSize - 1, color: "#555" }}>المجموع / Subtotal</span>
            <span style={{ fontSize: design.bodyFontSize - 1, fontFamily: "'Outfit', sans-serif" }}>{formatCurrency(invoice.subtotal, currency)}</span>
          </div>
          {(invoice.discountTotal ?? 0) > 0 && (
            <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid #eee", padding: "3px 0" }}>
              <span style={{ fontSize: design.bodyFontSize - 1, color: "#555" }}>الخصم / Discount</span>
              <span style={{ fontSize: design.bodyFontSize - 1, fontFamily: "'Outfit', sans-serif" }}>-{formatCurrency(invoice.discountTotal!, currency)}</span>
            </div>
          )}
          <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid #eee", padding: "3px 0" }}>
            <span style={{ fontSize: design.bodyFontSize - 1, color: "#555" }}>المبلغ الخاضع / Taxable</span>
            <span style={{ fontSize: design.bodyFontSize - 1, fontFamily: "'Outfit', sans-serif" }}>{formatCurrency(taxableAmount, currency)}</span>
          </div>
          <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid #eee", padding: "3px 0" }}>
            <span style={{ fontSize: design.bodyFontSize - 1, color: "#555" }}>الضريبة / VAT ({invoice.taxRate}%)</span>
            <span style={{ fontSize: design.bodyFontSize - 1, fontFamily: "'Outfit', sans-serif" }}>{formatCurrency(invoice.taxAmount, currency)}</span>
          </div>
          <div style={{
            display: "flex",
            justifyContent: "space-between",
            borderTop: `2px solid ${isModern || isElegant ? design.accentColor : design.primaryColor}`,
            paddingTop: isModern ? 6 : 5,
            paddingBottom: isModern ? 6 : 0,
            paddingLeft: isModern ? 6 : 0,
            paddingRight: isModern ? 6 : 0,
            marginTop: 2,
            ...(isModern ? { backgroundColor: `${design.accentColor}15`, borderRadius: 4 } : {}),
          }}>
            <strong style={{ fontSize: design.bodyFontSize + 2 }}>الإجمالي / Grand Total</strong>
            <strong style={{
              fontSize: design.bodyFontSize + 2,
              fontFamily: "'Outfit', sans-serif",
              ...(isModern ? { color: design.accentColor } : {}),
            }}>
              {formatCurrency(invoice.total, currency)}
            </strong>
          </div>
        </div>
      </div>

      {/* QR Code */}
      {design.showQrCode && invoice.qrCode && (
        <div style={{ textAlign: "center", marginBottom: 12 * sp }}>
          <QrCodeImage data={invoice.qrCode} size={120} />
        </div>
      )}

      {/* Notes */}
      {design.showNotes && invoice.notes && (
        <div style={{ marginBottom: 12 * sp, padding: 8, border: "1px solid #eee", fontSize: design.bodyFontSize - 1 }}>
          <strong>ملاحظات / Notes:</strong> {invoice.notes}
        </div>
      )}

      {/* Footer */}
      <div style={{
        textAlign: "center",
        fontSize: design.bodyFontSize - 2,
        color: "#999",
        borderTop: "1px solid #ddd",
        paddingTop: 8,
        marginTop: "auto",
      }}>
        {design.footerText || design.footerTextEn ? (
          <>
            {design.footerText && <div>{design.footerText}</div>}
            {design.footerTextEn && <div style={{ direction: "ltr" }}>{design.footerTextEn}</div>}
          </>
        ) : (
          <>
            {defaultFooterAr} / {defaultFooterEn}
          </>
        )}
      </div>
    </div>
  );
}

/* =============================================
   Main Component
   ============================================= */
export function InvoicePrintView({ invoice, settings, design = DEFAULT_INVOICE_DESIGN }: InvoicePrintViewProps) {
  const typeLabel = getInvoiceTypeLabel(invoice);
  const currency = invoice.currency || settings.currency || "";
  const logoUrl = settings.logoUrl;

  return (
    <div className="print-only">
      {/* A4 Layout — inline styles, matches the settings preview exactly */}
      <A4View invoice={invoice} settings={settings} design={design} />

      {/* Receipt 80mm Layout */}
      <div className="print-receipt-80-view inv-print inv-receipt inv-receipt-80" dir="rtl">
        <div className="inv-receipt-header">
          {logoUrl && <img src={logoUrl} alt="" className="inv-receipt-logo" />}
          <strong className="inv-receipt-biz-name">{settings.businessName}</strong>
          {settings.businessNameEn && <div className="inv-receipt-biz-en">{settings.businessNameEn}</div>}
          {settings.businessAddress && <div className="inv-receipt-detail">{settings.businessAddress}</div>}
          {settings.businessPhone && <div className="inv-receipt-detail" style={{ direction: "ltr" }}>{settings.businessPhone}</div>}
          {(settings.taxRegistrationNumber || settings.taxNumber) && (
            <div className="inv-receipt-detail inv-receipt-trn">
              الرقم الضريبي: {settings.taxRegistrationNumber || settings.taxNumber}
            </div>
          )}
        </div>

        <div className="inv-print-separator" />

        <div className="inv-receipt-type">{typeLabel.ar}</div>

        <div className="inv-print-separator" />

        <div className="inv-receipt-meta">
          <div>رقم: {invoice.invoiceNumber}</div>
          <div>التاريخ: {invoice.date}</div>
          <div>العميل: {invoice.clientName}</div>
        </div>

        <div className="inv-print-separator" />

        {invoice.items.map((item, i) => (
          <div key={i} className="inv-receipt-item">
            <div>{item.description}</div>
            <div className="inv-receipt-item-line">
              <span>{item.quantity} × {item.unitPrice.toFixed(2)}</span>
              <span>{item.total.toFixed(2)}</span>
            </div>
          </div>
        ))}

        <div className="inv-print-separator" />

        <div className="inv-receipt-totals">
          <div className="inv-receipt-totals-row">
            <span>المجموع</span>
            <span>{invoice.subtotal.toFixed(2)}</span>
          </div>
          {(invoice.discountTotal ?? 0) > 0 && (
            <div className="inv-receipt-totals-row">
              <span>الخصم</span>
              <span>-{invoice.discountTotal!.toFixed(2)}</span>
            </div>
          )}
          <div className="inv-receipt-totals-row">
            <span>الضريبة ({invoice.taxRate}%)</span>
            <span>{invoice.taxAmount.toFixed(2)}</span>
          </div>
        </div>
        <div className="inv-receipt-grand-total">
          <span>الإجمالي</span>
          <span>{formatCurrency(invoice.total, currency)}</span>
        </div>

        {design.showQrCode && invoice.qrCode && (
          <div className="inv-print-qr inv-receipt-qr">
            <QrCodeImage data={invoice.qrCode} size={100} />
          </div>
        )}

        <div className="inv-print-separator-star">- - - - - - - - - - - -</div>

        <div className="inv-receipt-thanks">
          <div>شكراً لزيارتكم</div>
          <div style={{ direction: "ltr" }}>Thank you for visiting</div>
        </div>
      </div>

      {/* Receipt 58mm Layout */}
      <div className="print-receipt-58-view inv-print inv-receipt inv-receipt-58" dir="rtl">
        <div className="inv-receipt-header">
          {logoUrl && <img src={logoUrl} alt="" className="inv-receipt-logo" />}
          <strong className="inv-receipt-biz-name">{settings.businessName}</strong>
          {(settings.taxRegistrationNumber || settings.taxNumber) && (
            <div className="inv-receipt-detail">
              {settings.taxRegistrationNumber || settings.taxNumber}
            </div>
          )}
        </div>

        <div className="inv-print-separator" />

        <div className="inv-receipt-type">{typeLabel.ar}</div>

        <div className="inv-print-separator" />

        <div className="inv-receipt-meta">
          <div>{invoice.invoiceNumber}</div>
          <div>{invoice.date}</div>
          <div>{invoice.clientName}</div>
        </div>

        <div className="inv-print-separator" />

        {invoice.items.map((item, i) => (
          <div key={i} className="inv-receipt-item">
            <div>{item.description}</div>
            <div className="inv-receipt-item-line">
              <span>{item.quantity}×{item.unitPrice.toFixed(2)}</span>
              <span>{item.total.toFixed(2)}</span>
            </div>
          </div>
        ))}

        <div className="inv-print-separator" />

        <div className="inv-receipt-totals">
          <div className="inv-receipt-totals-row">
            <span>المجموع</span>
            <span>{invoice.subtotal.toFixed(2)}</span>
          </div>
          {invoice.taxAmount > 0 && (
            <div className="inv-receipt-totals-row">
              <span>الضريبة</span>
              <span>{invoice.taxAmount.toFixed(2)}</span>
            </div>
          )}
        </div>
        <div className="inv-receipt-grand-total">
          <span>الإجمالي</span>
          <span>{invoice.total.toFixed(2)}</span>
        </div>

        {design.showQrCode && invoice.qrCode && (
          <div className="inv-print-qr inv-receipt-qr">
            <QrCodeImage data={invoice.qrCode} size={80} />
          </div>
        )}

        <div className="inv-print-separator-star">- - - - - - -</div>

        <div className="inv-receipt-thanks">
          شكراً لزيارتكم
        </div>
      </div>
    </div>
  );
}
