export const colorOptions = [
  { name: "Gold", value: "#C4956A" },
  { name: "Green", value: "#7ECB8B" },
  { name: "Purple", value: "#8B7FF5" },
  { name: "Blue", value: "#5B9BD5" },
  { name: "Rose", value: "#E07B7B" },
  { name: "Teal", value: "#4FD1C5" },
  { name: "Amber", value: "#F59E0B" },
  { name: "Indigo", value: "#6366F1" },
  { name: "Coral", value: "#F97316" },
  { name: "Pink", value: "#EC4899" },
] as const;

export const DEFAULT_COLOR = "#C4956A";

interface PaletteVars {
  "--background": string;
  "--foreground": string;
  "--card": string;
  "--card-foreground": string;
  "--popover": string;
  "--popover-foreground": string;
  "--primary": string;
  "--primary-foreground": string;
  "--secondary": string;
  "--secondary-foreground": string;
  "--muted": string;
  "--muted-foreground": string;
  "--accent": string;
  "--accent-foreground": string;
  "--destructive": string;
  "--destructive-foreground": string;
  "--border": string;
  "--input": string;
  "--ring": string;
  "--gold": string;
  "--gold-light": string;
  "--green": string;
  "--red": string;
  "--sidebar": string;
  "--sidebar-foreground": string;
  "--sidebar-active": string;
  "--chart-1": string;
  "--chart-2": string;
  "--chart-3": string;
  "--chart-4": string;
  "--chart-5": string;
}

export const COLOR_PALETTES: Record<string, { dark: PaletteVars; light: PaletteVars }> = {
  // ─── Gold (warm brown undertones) ───
  "#C4956A": {
    dark: {
      "--background": "#1A1614",
      "--foreground": "#F5EDE6",
      "--card": "#231F1C",
      "--card-foreground": "#F5EDE6",
      "--popover": "#231F1C",
      "--popover-foreground": "#F5EDE6",
      "--primary": "#C4956A",
      "--primary-foreground": "#1A1614",
      "--secondary": "#2A2522",
      "--secondary-foreground": "#F5EDE6",
      "--muted": "#2A2522",
      "--muted-foreground": "#A89B91",
      "--accent": "#C4956A",
      "--accent-foreground": "#1A1614",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#F5EDE6",
      "--border": "#3A3330",
      "--input": "#3A3330",
      "--ring": "#C4956A",
      "--gold": "#C4956A",
      "--gold-light": "#D4A97A",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#151210",
      "--sidebar-foreground": "#A89B91",
      "--sidebar-active": "#C4956A",
      "--chart-1": "#C4956A",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#E07B7B",
      "--chart-4": "#8B7FF5",
      "--chart-5": "#F5C26B",
    },
    light: {
      "--background": "#FAF7F5",
      "--foreground": "#1A1614",
      "--card": "#FFFFFF",
      "--card-foreground": "#1A1614",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1A1614",
      "--primary": "#C4956A",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#F0EBE7",
      "--secondary-foreground": "#1A1614",
      "--muted": "#F0EBE7",
      "--muted-foreground": "#6B5E54",
      "--accent": "#C4956A",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#FFFFFF",
      "--border": "#E0D8D0",
      "--input": "#E0D8D0",
      "--ring": "#C4956A",
      "--gold": "#C4956A",
      "--gold-light": "#D4A97A",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#FFFFFF",
      "--sidebar-foreground": "#6B5E54",
      "--sidebar-active": "#C4956A",
      "--chart-1": "#C4956A",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#E07B7B",
      "--chart-4": "#8B7FF5",
      "--chart-5": "#F5C26B",
    },
  },

  // ─── Green (cool forest undertones) ───
  "#7ECB8B": {
    dark: {
      "--background": "#141A16",
      "--foreground": "#E6F5EB",
      "--card": "#1C231F",
      "--card-foreground": "#E6F5EB",
      "--popover": "#1C231F",
      "--popover-foreground": "#E6F5EB",
      "--primary": "#7ECB8B",
      "--primary-foreground": "#141A16",
      "--secondary": "#222A25",
      "--secondary-foreground": "#E6F5EB",
      "--muted": "#222A25",
      "--muted-foreground": "#91A89B",
      "--accent": "#7ECB8B",
      "--accent-foreground": "#141A16",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#E6F5EB",
      "--border": "#303A33",
      "--input": "#303A33",
      "--ring": "#7ECB8B",
      "--gold": "#7ECB8B",
      "--gold-light": "#9EDAAB",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#101512",
      "--sidebar-foreground": "#91A89B",
      "--sidebar-active": "#7ECB8B",
      "--chart-1": "#7ECB8B",
      "--chart-2": "#C4956A",
      "--chart-3": "#E07B7B",
      "--chart-4": "#8B7FF5",
      "--chart-5": "#F5C26B",
    },
    light: {
      "--background": "#F5FAF7",
      "--foreground": "#141A16",
      "--card": "#FFFFFF",
      "--card-foreground": "#141A16",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#141A16",
      "--primary": "#5DB870",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#E7F0EB",
      "--secondary-foreground": "#141A16",
      "--muted": "#E7F0EB",
      "--muted-foreground": "#546B5E",
      "--accent": "#5DB870",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#FFFFFF",
      "--border": "#D0E0D8",
      "--input": "#D0E0D8",
      "--ring": "#5DB870",
      "--gold": "#5DB870",
      "--gold-light": "#9EDAAB",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#FFFFFF",
      "--sidebar-foreground": "#546B5E",
      "--sidebar-active": "#5DB870",
      "--chart-1": "#5DB870",
      "--chart-2": "#C4956A",
      "--chart-3": "#E07B7B",
      "--chart-4": "#8B7FF5",
      "--chart-5": "#F5C26B",
    },
  },

  // ─── Purple (cool violet undertones) ───
  "#8B7FF5": {
    dark: {
      "--background": "#17141A",
      "--foreground": "#EDE6F5",
      "--card": "#1F1C23",
      "--card-foreground": "#EDE6F5",
      "--popover": "#1F1C23",
      "--popover-foreground": "#EDE6F5",
      "--primary": "#8B7FF5",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#25222A",
      "--secondary-foreground": "#EDE6F5",
      "--muted": "#25222A",
      "--muted-foreground": "#9B91A8",
      "--accent": "#8B7FF5",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#EDE6F5",
      "--border": "#33303A",
      "--input": "#33303A",
      "--ring": "#8B7FF5",
      "--gold": "#8B7FF5",
      "--gold-light": "#A99AF7",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#121015",
      "--sidebar-foreground": "#9B91A8",
      "--sidebar-active": "#8B7FF5",
      "--chart-1": "#8B7FF5",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#E07B7B",
      "--chart-4": "#C4956A",
      "--chart-5": "#F5C26B",
    },
    light: {
      "--background": "#F7F5FA",
      "--foreground": "#17141A",
      "--card": "#FFFFFF",
      "--card-foreground": "#17141A",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#17141A",
      "--primary": "#7366E0",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#EBE7F0",
      "--secondary-foreground": "#17141A",
      "--muted": "#EBE7F0",
      "--muted-foreground": "#5E546B",
      "--accent": "#7366E0",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#FFFFFF",
      "--border": "#D8D0E0",
      "--input": "#D8D0E0",
      "--ring": "#7366E0",
      "--gold": "#7366E0",
      "--gold-light": "#A99AF7",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#FFFFFF",
      "--sidebar-foreground": "#5E546B",
      "--sidebar-active": "#7366E0",
      "--chart-1": "#7366E0",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#E07B7B",
      "--chart-4": "#C4956A",
      "--chart-5": "#F5C26B",
    },
  },

  // ─── Blue (cool slate undertones) ───
  "#5B9BD5": {
    dark: {
      "--background": "#14171A",
      "--foreground": "#E6EDF5",
      "--card": "#1C2023",
      "--card-foreground": "#E6EDF5",
      "--popover": "#1C2023",
      "--popover-foreground": "#E6EDF5",
      "--primary": "#5B9BD5",
      "--primary-foreground": "#14171A",
      "--secondary": "#22252A",
      "--secondary-foreground": "#E6EDF5",
      "--muted": "#22252A",
      "--muted-foreground": "#91A0A8",
      "--accent": "#5B9BD5",
      "--accent-foreground": "#14171A",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#E6EDF5",
      "--border": "#30333A",
      "--input": "#30333A",
      "--ring": "#5B9BD5",
      "--gold": "#5B9BD5",
      "--gold-light": "#7DB3E0",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#101215",
      "--sidebar-foreground": "#91A0A8",
      "--sidebar-active": "#5B9BD5",
      "--chart-1": "#5B9BD5",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#E07B7B",
      "--chart-4": "#8B7FF5",
      "--chart-5": "#F5C26B",
    },
    light: {
      "--background": "#F5F7FA",
      "--foreground": "#14171A",
      "--card": "#FFFFFF",
      "--card-foreground": "#14171A",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#14171A",
      "--primary": "#4A89C2",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#E7EBF0",
      "--secondary-foreground": "#14171A",
      "--muted": "#E7EBF0",
      "--muted-foreground": "#546068",
      "--accent": "#4A89C2",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#FFFFFF",
      "--border": "#D0D8E0",
      "--input": "#D0D8E0",
      "--ring": "#4A89C2",
      "--gold": "#4A89C2",
      "--gold-light": "#7DB3E0",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#FFFFFF",
      "--sidebar-foreground": "#546068",
      "--sidebar-active": "#4A89C2",
      "--chart-1": "#4A89C2",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#E07B7B",
      "--chart-4": "#8B7FF5",
      "--chart-5": "#F5C26B",
    },
  },

  // ─── Rose (warm pink undertones) ───
  "#E07B7B": {
    dark: {
      "--background": "#1A1416",
      "--foreground": "#F5E6ED",
      "--card": "#231C1F",
      "--card-foreground": "#F5E6ED",
      "--popover": "#231C1F",
      "--popover-foreground": "#F5E6ED",
      "--primary": "#E07B7B",
      "--primary-foreground": "#1A1416",
      "--secondary": "#2A2225",
      "--secondary-foreground": "#F5E6ED",
      "--muted": "#2A2225",
      "--muted-foreground": "#A891A0",
      "--accent": "#E07B7B",
      "--accent-foreground": "#1A1416",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#F5E6ED",
      "--border": "#3A3033",
      "--input": "#3A3033",
      "--ring": "#E07B7B",
      "--gold": "#E07B7B",
      "--gold-light": "#E89A9A",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#151012",
      "--sidebar-foreground": "#A891A0",
      "--sidebar-active": "#E07B7B",
      "--chart-1": "#E07B7B",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#C4956A",
      "--chart-4": "#8B7FF5",
      "--chart-5": "#F5C26B",
    },
    light: {
      "--background": "#FAF5F7",
      "--foreground": "#1A1416",
      "--card": "#FFFFFF",
      "--card-foreground": "#1A1416",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1A1416",
      "--primary": "#D06565",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#F0E7EB",
      "--secondary-foreground": "#1A1416",
      "--muted": "#F0E7EB",
      "--muted-foreground": "#6B545E",
      "--accent": "#D06565",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#FFFFFF",
      "--border": "#E0D0D8",
      "--input": "#E0D0D8",
      "--ring": "#D06565",
      "--gold": "#D06565",
      "--gold-light": "#E89A9A",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#FFFFFF",
      "--sidebar-foreground": "#6B545E",
      "--sidebar-active": "#D06565",
      "--chart-1": "#D06565",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#C4956A",
      "--chart-4": "#8B7FF5",
      "--chart-5": "#F5C26B",
    },
  },

  // ─── Teal (cool turquoise undertones) ───
  "#4FD1C5": {
    dark: {
      "--background": "#141A19",
      "--foreground": "#E6F5F3",
      "--card": "#1C2322",
      "--card-foreground": "#E6F5F3",
      "--popover": "#1C2322",
      "--popover-foreground": "#E6F5F3",
      "--primary": "#4FD1C5",
      "--primary-foreground": "#141A19",
      "--secondary": "#222A29",
      "--secondary-foreground": "#E6F5F3",
      "--muted": "#222A29",
      "--muted-foreground": "#91A8A5",
      "--accent": "#4FD1C5",
      "--accent-foreground": "#141A19",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#E6F5F3",
      "--border": "#303A38",
      "--input": "#303A38",
      "--ring": "#4FD1C5",
      "--gold": "#4FD1C5",
      "--gold-light": "#7DDDD4",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#101515",
      "--sidebar-foreground": "#91A8A5",
      "--sidebar-active": "#4FD1C5",
      "--chart-1": "#4FD1C5",
      "--chart-2": "#C4956A",
      "--chart-3": "#E07B7B",
      "--chart-4": "#8B7FF5",
      "--chart-5": "#F5C26B",
    },
    light: {
      "--background": "#F5FAFA",
      "--foreground": "#141A19",
      "--card": "#FFFFFF",
      "--card-foreground": "#141A19",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#141A19",
      "--primary": "#3BBFB3",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#E7F0EF",
      "--secondary-foreground": "#141A19",
      "--muted": "#E7F0EF",
      "--muted-foreground": "#546B68",
      "--accent": "#3BBFB3",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#FFFFFF",
      "--border": "#D0E0DE",
      "--input": "#D0E0DE",
      "--ring": "#3BBFB3",
      "--gold": "#3BBFB3",
      "--gold-light": "#7DDDD4",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#FFFFFF",
      "--sidebar-foreground": "#546B68",
      "--sidebar-active": "#3BBFB3",
      "--chart-1": "#3BBFB3",
      "--chart-2": "#C4956A",
      "--chart-3": "#E07B7B",
      "--chart-4": "#8B7FF5",
      "--chart-5": "#F5C26B",
    },
  },

  // ─── Amber (warm honey undertones) ───
  "#F59E0B": {
    dark: {
      "--background": "#1A1710",
      "--foreground": "#F5EFE0",
      "--card": "#232017",
      "--card-foreground": "#F5EFE0",
      "--popover": "#232017",
      "--popover-foreground": "#F5EFE0",
      "--primary": "#F59E0B",
      "--primary-foreground": "#1A1710",
      "--secondary": "#2A271E",
      "--secondary-foreground": "#F5EFE0",
      "--muted": "#2A271E",
      "--muted-foreground": "#A8A080",
      "--accent": "#F59E0B",
      "--accent-foreground": "#1A1710",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#F5EFE0",
      "--border": "#3A3728",
      "--input": "#3A3728",
      "--ring": "#F59E0B",
      "--gold": "#F59E0B",
      "--gold-light": "#FBB740",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#151308",
      "--sidebar-foreground": "#A8A080",
      "--sidebar-active": "#F59E0B",
      "--chart-1": "#F59E0B",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#E07B7B",
      "--chart-4": "#8B7FF5",
      "--chart-5": "#5B9BD5",
    },
    light: {
      "--background": "#FAF8F0",
      "--foreground": "#1A1710",
      "--card": "#FFFFFF",
      "--card-foreground": "#1A1710",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1A1710",
      "--primary": "#D98E0A",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#F0EDE3",
      "--secondary-foreground": "#1A1710",
      "--muted": "#F0EDE3",
      "--muted-foreground": "#6B6545",
      "--accent": "#D98E0A",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#FFFFFF",
      "--border": "#E0DBC8",
      "--input": "#E0DBC8",
      "--ring": "#D98E0A",
      "--gold": "#D98E0A",
      "--gold-light": "#FBB740",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#FFFFFF",
      "--sidebar-foreground": "#6B6545",
      "--sidebar-active": "#D98E0A",
      "--chart-1": "#D98E0A",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#E07B7B",
      "--chart-4": "#8B7FF5",
      "--chart-5": "#5B9BD5",
    },
  },

  // ─── Indigo (deep blue-violet undertones) ───
  "#6366F1": {
    dark: {
      "--background": "#15141A",
      "--foreground": "#E8E6F5",
      "--card": "#1D1C25",
      "--card-foreground": "#E8E6F5",
      "--popover": "#1D1C25",
      "--popover-foreground": "#E8E6F5",
      "--primary": "#6366F1",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#24222C",
      "--secondary-foreground": "#E8E6F5",
      "--muted": "#24222C",
      "--muted-foreground": "#9591AC",
      "--accent": "#6366F1",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#E8E6F5",
      "--border": "#32303C",
      "--input": "#32303C",
      "--ring": "#6366F1",
      "--gold": "#6366F1",
      "--gold-light": "#8B8DF5",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#100F15",
      "--sidebar-foreground": "#9591AC",
      "--sidebar-active": "#6366F1",
      "--chart-1": "#6366F1",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#E07B7B",
      "--chart-4": "#C4956A",
      "--chart-5": "#F5C26B",
    },
    light: {
      "--background": "#F6F5FA",
      "--foreground": "#15141A",
      "--card": "#FFFFFF",
      "--card-foreground": "#15141A",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#15141A",
      "--primary": "#5558E0",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#EBEAF2",
      "--secondary-foreground": "#15141A",
      "--muted": "#EBEAF2",
      "--muted-foreground": "#58546E",
      "--accent": "#5558E0",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#FFFFFF",
      "--border": "#D5D0E2",
      "--input": "#D5D0E2",
      "--ring": "#5558E0",
      "--gold": "#5558E0",
      "--gold-light": "#8B8DF5",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#FFFFFF",
      "--sidebar-foreground": "#58546E",
      "--sidebar-active": "#5558E0",
      "--chart-1": "#5558E0",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#E07B7B",
      "--chart-4": "#C4956A",
      "--chart-5": "#F5C26B",
    },
  },

  // ─── Coral (warm orange undertones) ───
  "#F97316": {
    dark: {
      "--background": "#1A1514",
      "--foreground": "#F5EAE6",
      "--card": "#231E1C",
      "--card-foreground": "#F5EAE6",
      "--popover": "#231E1C",
      "--popover-foreground": "#F5EAE6",
      "--primary": "#F97316",
      "--primary-foreground": "#1A1514",
      "--secondary": "#2A2422",
      "--secondary-foreground": "#F5EAE6",
      "--muted": "#2A2422",
      "--muted-foreground": "#A8978B",
      "--accent": "#F97316",
      "--accent-foreground": "#1A1514",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#F5EAE6",
      "--border": "#3A3230",
      "--input": "#3A3230",
      "--ring": "#F97316",
      "--gold": "#F97316",
      "--gold-light": "#FB9A4F",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#151110",
      "--sidebar-foreground": "#A8978B",
      "--sidebar-active": "#F97316",
      "--chart-1": "#F97316",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#8B7FF5",
      "--chart-4": "#5B9BD5",
      "--chart-5": "#F5C26B",
    },
    light: {
      "--background": "#FAF7F5",
      "--foreground": "#1A1514",
      "--card": "#FFFFFF",
      "--card-foreground": "#1A1514",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1A1514",
      "--primary": "#E06610",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#F0EBE7",
      "--secondary-foreground": "#1A1514",
      "--muted": "#F0EBE7",
      "--muted-foreground": "#6B5B50",
      "--accent": "#E06610",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#FFFFFF",
      "--border": "#E0D6D0",
      "--input": "#E0D6D0",
      "--ring": "#E06610",
      "--gold": "#E06610",
      "--gold-light": "#FB9A4F",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#FFFFFF",
      "--sidebar-foreground": "#6B5B50",
      "--sidebar-active": "#E06610",
      "--chart-1": "#E06610",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#8B7FF5",
      "--chart-4": "#5B9BD5",
      "--chart-5": "#F5C26B",
    },
  },

  // ─── Pink (vibrant fuchsia undertones) ───
  "#EC4899": {
    dark: {
      "--background": "#1A1417",
      "--foreground": "#F5E6EF",
      "--card": "#231C20",
      "--card-foreground": "#F5E6EF",
      "--popover": "#231C20",
      "--popover-foreground": "#F5E6EF",
      "--primary": "#EC4899",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#2A2226",
      "--secondary-foreground": "#F5E6EF",
      "--muted": "#2A2226",
      "--muted-foreground": "#A891A0",
      "--accent": "#EC4899",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#F5E6EF",
      "--border": "#3A3035",
      "--input": "#3A3035",
      "--ring": "#EC4899",
      "--gold": "#EC4899",
      "--gold-light": "#F27AB5",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#151012",
      "--sidebar-foreground": "#A891A0",
      "--sidebar-active": "#EC4899",
      "--chart-1": "#EC4899",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#C4956A",
      "--chart-4": "#8B7FF5",
      "--chart-5": "#F5C26B",
    },
    light: {
      "--background": "#FAF5F8",
      "--foreground": "#1A1417",
      "--card": "#FFFFFF",
      "--card-foreground": "#1A1417",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1A1417",
      "--primary": "#D63D87",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#F0E7EC",
      "--secondary-foreground": "#1A1417",
      "--muted": "#F0E7EC",
      "--muted-foreground": "#6B5460",
      "--accent": "#D63D87",
      "--accent-foreground": "#FFFFFF",
      "--destructive": "#E07B7B",
      "--destructive-foreground": "#FFFFFF",
      "--border": "#E0D0DA",
      "--input": "#E0D0DA",
      "--ring": "#D63D87",
      "--gold": "#D63D87",
      "--gold-light": "#F27AB5",
      "--green": "#7ECB8B",
      "--red": "#E07B7B",
      "--sidebar": "#FFFFFF",
      "--sidebar-foreground": "#6B5460",
      "--sidebar-active": "#D63D87",
      "--chart-1": "#D63D87",
      "--chart-2": "#7ECB8B",
      "--chart-3": "#C4956A",
      "--chart-4": "#8B7FF5",
      "--chart-5": "#F5C26B",
    },
  },
};

export function applyColorPalette(hex: string, theme: "dark" | "light") {
  const palette = COLOR_PALETTES[hex]?.[theme] ?? COLOR_PALETTES[DEFAULT_COLOR][theme];
  const root = document.documentElement;
  for (const [key, value] of Object.entries(palette)) {
    root.style.setProperty(key, value);
  }
}
